export const LOAD_CONTROLLERS_LIST_REQUESTED = 'lib/api/controllers/LOAD_CONTROLLERS_LIST_REQUESTED';
export const LOAD_CONTROLLERS_LIST_PROCESSING = 'lib/api/controllers/LOAD_CONTROLLERS_LIST_PROCESSING';
export const LOAD_CONTROLLERS_LIST_SUCCEED = 'lib/api/controllers/LOAD_CONTROLLERS_LIST_SUCCEED';
export const LOAD_CONTROLLERS_LIST_FAILED = 'lib/api/controllers/LOAD_CONTROLLERS_LIST_FAILED';

export const REGISTER_CONTROLLER_REQUESTED = 'lib/api/controllers/REGISTER_CONTROLLER_REQUESTED';
export const REGISTER_CONTROLLER_PROCESSING = 'lib/api/controllers/REGISTER_CONTROLLER_PROCESSING';
export const REGISTER_CONTROLLER_SUCCEED = 'lib/api/controllers/REGISTER_CONTROLLER_SUCCEED';
export const REGISTER_CONTROLLER_FAILED = 'lib/api/controllers/REGISTER_CONTROLLER_FAILED';